sudo: required
services:
  - docker

before_install:
  - docker build -t mike21docker/docker-react -f Dockerfile.dev .

script:
  - docker container run mike21docker/docker-react npm run test -- --coverage